# Generated by Django 3.0.4 on 2020-03-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=10000)),
                ('password', models.CharField(max_length=20)),
                ('public', models.BooleanField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(default='큰사자가 답변을 달러 뛰어오고 있습니다. 잠시만 기다려 주세요.', on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='theapp.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='theapp.Question'),
        ),
    ]
